# Data Loading, storage and File formats

Data Frame

In [10]:

import pandas as pd
data={
    "Name":["John","Anna","Peter","karan"],
    "Age":[28,24,35,68],
    "City":["New York","USA","Paris","Landon"],
    "Grade":["A","B","C","A+"]
}
df=pd.DataFrame(data)
df

    Name  Age      City Grade
0   John   28  New York     A
1   Anna   24       USA     B
2  Peter   35     Paris     C
3  karan   68    Landon    A+

In [16]:
print("Shape of the dataframe:",df.shape)
print("Head with 2 rows: \n",df.head(2))
print("Tail of 2 row:\n",df.tail(2))
print("Column:",df.columns.tolist())
print("Data Type:\n ",df.dtypes)
print("Data Information:\n ",df.info())
print("Statistic of DataFrame:\n ",df.describe())

Shape of the dataframe: (4, 4)
Head with 2 rows:
    Name  Age      City Grade
0  John   28  New York     A
1  Anna   24       USA     B
Tail of 2 row:
     Name  Age    City Grade
2  Peter   35   Paris     C
3  karan   68  Landon    A+
Column: ['Name', 'Age', 'City', 'Grade']
Data Type:
  Name     object
Age       int64
City     object
Grade    object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Grade   4 non-null      object
dtypes: int64(1), object(3)
memory usage: 260.0+ bytes
Data Information:
  None
Statistic of DataFrame:
               Age
count   4.000000
mean   38.750000
std    20.022904
min    24.000000
25%    27.000000
50%    31.500000
75%    43.250000
max    68.000000

In [15]:
iris=pd.read_csv("/content/Iris.csv")
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [18]:
print(iris.shape)
print(iris.columns)
print(iris.dtypes)

(150, 6)
Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')
Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

#File Formats
1. csv
2. excel
3. json
4. parquet

csv

In [24]:

#Load the dataset in the format
iris.to_csv("iris_csvoutput.csv",index=False)
# read the saved dataset
iris_csv=pd.read_csv("/content/iris_csvoutput.csv")
iris_csv
print(iris_csv.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

excel

In [31]:
iris.to_excel("iris_exceloutput.xlsx",index=False)
#Load
iris_excel =pd.read_excel("/content/iris_exceloutput.xlsx")
print(iris_excel.tail(10))

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141            6.7           3.1            5.6           2.4
141  142            6.9           3.1            5.1           2.3
142  143            5.8           2.7            5.1           1.9
143  144            6.8           3.2            5.9           2.3
144  145            6.7           3.3            5.7           2.5
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
140  Iris-virginica
141  Iris-virginica
142  Iris-virginica
143  Iris-virginica
144  Iris-virginica
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

Json

In [36]:
#Json file format
iris.to_json("iris_jsonoutput.json",orient="records",indent=4)
#read the file
iris_json=pd.read_json("/content/iris_jsonoutput.json")
iris_json.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Parquet

In [40]:
#File format parquet
iris.to_parquet("iris_parquetoutput.parquet",index=False)
iris_parquet=pd.read_parquet("/content/iris_parquetoutput.parquet")
iris_parquet.head(3)

top 3 row :
    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [41]:
#Compare the size
import os
files={
    "iris_csvoutput.csv",
    "iris_exceloutput.xlsx",
    "iris_jsonoutput.json",
    "iris_parquetoutput.parquet"
}
for file in files:
  size = os.path.getsize(file)
  print(f"{file}:{size} bytes")

iris_csvoutput.csv:5107 bytes
iris_parquetoutput.parquet:5932 bytes
iris_exceloutput.xlsx:9208 bytes
iris_jsonoutput.json:26794 bytes

In [54]:
import pandas as pd

# Load the selected columns
iris_small = pd.read_csv(
    "/content/Iris.csv",
    usecols=["SepalLengthCm", "SepalWidthCm", "Species"]
)

print(iris_small.head(3))

   SepalLengthCm  SepalWidthCm      Species
0            5.1           3.5  Iris-setosa
1            4.9           3.0  Iris-setosa
2            4.7           3.2  Iris-setosa

In [55]:

# Filter the data
result = iris_small[iris_small["SepalLengthCm"] > 0]

print(result.head(3))

   SepalLengthCm  SepalWidthCm      Species
0            5.1           3.5  Iris-setosa
1            4.9           3.0  Iris-setosa
2            4.7           3.2  Iris-setosa

# include 5 more rows in the dataframe
convert to different file formats and compare the file size

In [52]:

# First 8 rows (3 original + 5 more)
iris_8 = iris_small.head(8)

print(iris_8)

# Compare file sizes
files = [
    "/content/iris.csv",
    "/content/iris.xlsx",
    "/content/iris.json",
    "/content/iris.parquet"
]

for file in files:
    size = os.path.getsize(file)
    print(f"{os.path.basename(file):20} {size:6} bytes ({size/1024:.2f} KB)")

   SepalLengthCm  SepalWidthCm      Species
0            5.1           3.5  Iris-setosa
1            4.9           3.0  Iris-setosa
2            4.7           3.2  Iris-setosa
3            4.6           3.1  Iris-setosa
4            5.0           3.6  Iris-setosa
5            5.4           3.9  Iris-setosa
6            4.6           3.4  Iris-setosa
7            5.0           3.4  Iris-setosa
iris.csv                195 bytes (0.19 KB)
iris.xlsx              5100 bytes (4.98 KB)
iris.json               690 bytes (0.67 KB)
iris.parquet           2479 bytes (2.42 KB)